package pathpatterntype

var singleTypesMap = map[Variant]bool{
	Invalid:       true,
	Root:          true,
	VariableDir:   true,
	App:           true,
	AppCore:       true,
	Id:            true,
	File:          true,
	Relative:      true,
	TempRoot:      true,
	AppInstalled:  true,
	Home:          true,
	User:          true,
	UsersRoot:     true,
	WebServerRoot: true,
	Packages:      true,
	Instructions:  true,
	Log:           true,
	Database:      true,
	Test:          true,
	Temp:          true,
	Prefix:        true,
	Downloads:     true,
	Extension:     true,
	Webserver:     true,
	Audit:         true,
	Random:        true,
	RandomUuid:    true,
	RandomNumber:  true,
	Specific:      true,
	Backup:        true,
	Ssl:           true,
	Config:        true,
	Users:         true,
}
